apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: eyo40q4gf-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:3c5419906300e666a0575d7dcacd7cf07380b512@sha256:66265d9e70f154ee698540ae0aa1a8b2f8daae9bbc733e8765d4e7e10bb6f0a1
          name: container-image
